FROM node:24-alpine AS build 
WORKDIR /app
ADD . /app
RUN npm install && \ npm run build 

FROM nginx:alpine AS runtime
LABEL project="my node project"
LABEL author="dev 6th"
COPY --from=build /app/build /user/share/nginx/html
EXPOSE 80
ENTRYPOINT ["node"]